// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkZS_2jMPED6k7NFN5XXIE7wBLzKizxbE',
    appId: '1:543325241068:web:3c9b1147c1adf86c1cefc9',
    messagingSenderId: '543325241068',
    projectId: 'attendance-management-sy-bd297',
    authDomain: 'attendance-management-sy-bd297.firebaseapp.com',
    storageBucket: 'attendance-management-sy-bd297.appspot.com',
    measurementId: 'G-Z57QHVEZGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNpZVgAVFnqXsvHBGOaCYxRkRy8MlPpUY',
    appId: '1:543325241068:android:65575bdf263d4bb01cefc9',
    messagingSenderId: '543325241068',
    projectId: 'attendance-management-sy-bd297',
    storageBucket: 'attendance-management-sy-bd297.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW9BF0upYWqtF1vF1RvjPoh6a4j7UPp40',
    appId: '1:543325241068:ios:b41cd938518f83421cefc9',
    messagingSenderId: '543325241068',
    projectId: 'attendance-management-sy-bd297',
    storageBucket: 'attendance-management-sy-bd297.appspot.com',
    iosBundleId: 'com.example.chattychin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW9BF0upYWqtF1vF1RvjPoh6a4j7UPp40',
    appId: '1:543325241068:ios:2ecc0d7ae19a14c81cefc9',
    messagingSenderId: '543325241068',
    projectId: 'attendance-management-sy-bd297',
    storageBucket: 'attendance-management-sy-bd297.appspot.com',
    iosBundleId: 'com.example.chattychin.RunnerTests',
  );
}
